# Generated by Django 2.1.7 on 2019-03-25 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('range_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendtable',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
